@baseUrl = http://localhost:5050

###
GET {{baseUrl}}/health
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/env
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/fibo/60
Content-Type: application/json
Accept: application/json
withCredentials: true
